###
#   Application Settings
###
server:
  port: 9000
spring:
  application:
    name: beer
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9871/eureka
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG

